name: build cicd

on:
  push:
    branches:
      - main # Ejecutar solo en la rama main

jobs:
  build-and-push:
    name: Push Docker Imagen
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Loguear en GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Construir y subir la imagen Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/leonelchauca/proyecto-arm-vue-app:latest .
          docker push ghcr.io/leonelchauca/proyecto-arm-vue-app:latest
